#!/bin/bash
dotfilesDir=$(pwd)

function linkDotfile {
  dest="${HOME}/${1}"
  dateStr=$(date +%Y-%m-%d-%H%M)

  if [ -h ~/${1} ]; then
    # Existing symlink
    echo "Removing existing symlink: ${dest}"
    rm ${dest}

  elif [ -f "${dest}" ]; then
    # Existing file
    echo "Backing up existing file: ${dest}"
    mv ${dest}{,.${dateStr}}

  elif [ -d "${dest}" ]; then
    # Existing dir
    echo "Backing up existing dir: ${dest}"
    mv ${dest}{,.${dateStr}}
  fi

  echo "Creating new symlink: ${dest}"
  ln -s ${dotfilesDir}/${1} ${dest}
}

# Needs homebrew to install
function install {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    echo "Installing: ${1}..."
    brew install $1
  else
    echo "Already installed: ${1}"
  fi
}

# Install Apps
install vim
install tmux
install iterm2
install romkatv/powerlevel10k/powerlevel10k

# Link dotfiles
linkDotfile .vim
linkDotfile .zshrc
linkDotfile .gitconfig
linkDotfile .p10k.zsh

# Update Git Submodules
git submodule init
git submodule update --remote --merge
