#!/bin/bash
dotfilesDir=$(pwd)

function linkDotfile {
  dest="${HOME}/${1}"
  dateStr=$(date +%Y-%m-%d-%H%M)

  if [ -h ~/${1} ]; then
    # Existing symlink
    echo "Removing existing symlink: ${dest}"
    rm ${dest}

  elif [ -f "${dest}" ]; then
    # Existing file
    echo "Backing up existing file: ${dest}"
    mv ${dest}{,.${dateStr}}

  elif [ -d "${dest}" ]; then
    # Existing dir
    echo "Backing up existing dir: ${dest}"
    mv ${dest}{,.${dateStr}}
  fi

  echo "Creating new symlink: ${dest}"
  ln -s ${dotfilesDir}/${1} ${dest}
}

# Needs homebrew to install
function install {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    echo "Installing: ${1}..."
    brew install $1
  else
    echo "Already installed: ${1}"
  fi
}

# Install xcode developer tools (git, etc...)
xcode-select --install 2> /dev/null

brew tap "d12frosted/emacs-plus"

# Update homebrew
brew update
brew upgrade
brew cleanup

# Install Apps
install vim
install neovim
install fzf
install bat
install ripgrep
install exa
install starship
install htop
install ffmpeg
install tmux
install antigen

# Link dotfiles
linkDotfile .config/nvim/init.vim
linkDotfile .config/nvim/coc-settings.json
linkDotfile .config/nvim/lua/plugins.lua
linkDotfile .config/nvim/autoload/plug.vim
linkDotfile .config/alacritty
linkDotfile .config/starship.toml
linkDotfile .zshrc
linkDotfile .gitconfig
linkDotfile .tmux.conf

# Update submodules
git submodule update --remote --merge
